@baseurl=http://localhost:7284

# Book the trip
GET {{baseurl}}/api/HttpStart?userId=me
Content-Type: application/json

###

@instanceId=d7cb54f6dccf4fd18afca4871522207e
@approved=true

# CheckStatus
GET {{baseurl}}/api/GetStatus?instanceid={{instanceId}}

###


# Approve
POST {{baseurl}}/api/Approve
Content-type: application/json

{
  "Approved": "{{approved}}",
  "InstanceId": "{{instanceId}}"
}